filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/asterisk/messages* # Добавили звездочку на случай ротации логов
  fields:
    pbx_id: ${PBX_NAME}
  fields_under_root: true          # Теперь это внутри блока инпута
  processors:
  - dissect:
      tokenizer: "[%{timestamp}] %{level}[%{pid}] %{file}: %{message}"
      field: "message"
      target_prefix: "asterisk"
      ignore_failure: true
  - replace:
      fields:
      - field: "message"
        pattern: '^\[.*?\] '
        replacement: ""
  - timestamp:
      field: "asterisk.timestamp"
      layouts:
        - "2006-01-02 15:04:05"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  # pipeline: "asterisk-parser"
  index: "raw-asterisk-logs"

setup.ilm.enabled: false
setup.data_stream.enabled: false
setup.template.name: "asterisk"
setup.template.pattern: "asterisk-*"