-- PJSIP VIEW создаются приложением (utils/pjsip_views.py) при создании АТС
-- и при POST /instances/{id}/reload.
--
-- Для уже существующих инстансов: вызовите reload по каждому id или пересоздайте VIEW вручную:
--   ps_aors_inst_<instance_id>      — WHERE reg_server = '<имя_АТС>'
--   ps_endpoints_inst_<id>         — JOIN ps_aors по aors_id
--   ps_auths_inst_<id>             — auths endpoint'ов этого инстанса
--   ps_contacts_inst_<id>          — contacts по endpoint.id
--   ps_endpoint_id_ips_inst_<id>    — identify по endpoint.id
--
-- extconfig.conf на диске должен указывать VIEW, не базовые таблицы ps_*.
