[settings]
; имя_объекта => драйвер,имя_коннектора_из_res_odbc,имя_таблицы
ps_endpoints => odbc,asterisk_cdr,ps_endpoints
ps_auths => odbc,asterisk_cdr,ps_auths
ps_aors => odbc,asterisk_cdr,ps_aors
ps_domain_aliases => odbc,asterisk_cdr,ps_domain_aliases
ps_endpoint_id_ips => odbc,asterisk_cdr,ps_endpoint_id_ips
ps_contacts => odbc,asterisk_cdr,ps_contacts