[from-internal]
exten => _XXX,1,NoOp(Звонок на внутренний номер ${EXTEN})
exten => _XXX,n,Dial(PJSIP/${EXTEN},20)
exten => _XXX,n,Hangup()

[from-external]
exten => 777,1,NoOp(Входящий звонок от клиента ${CALLERID(all)})
same => n,Answer()
same => n,Dial(PJSIP/101,20)
same => n,Hangup()
