# [from-internal]
# exten => 600,1,Answer()

# same => n,Echo()
# same => n,Hangup()

# exten => 101,1,Dial(PJSIP/101)
[from-internal]
exten => _XXX,1,NoOp(Звонок на внутренний номер ${EXTEN})
# same => n,Dial(PJSIP/${EXTEN},20)
same => n,Answer()
same => n, Echo()
same => n,Hangup()

[from-external]
exten => 777,1,NoOp(Входящий звонок от клиента ${CALLERID(all)})
same => n,Answer()
same => n,Dial(PJSIP/101,20)
same => n,Hangup()
            