
[res_pjsip]
endpoint=config,pjsip.conf
endpoint=realtime,ps_endpoints
auth=config,pjsip.conf
auth=realtime,ps_auths
aor=config,pjsip.conf
aor=realtime,ps_aors
contact=realtime,ps_contacts

[res_pjsip_endpoint_identifier_ip]
identify=config,pjsip.conf
identify=realtime,ps_endpoint_id_ips

[res_pjsip_endpoint_identifier_user]
endpoint=realtime,ps_endpoints