[res_pjsip]
endpoint=config,pjsip_users.conf,criteria=type=endpoint
auth=config,pjsip_users.conf,criteria=type=auth
aor=config,pjsip_users.conf,criteria=type=aor
contact=realtime,ps_contacts

[res_pjsip_endpoint_identifier_ip]
identify=realtime,ps_endpoint_id_ips

[res_pjsip_endpoint_identifier_user]
endpoint=config,pjsip_users.conf,criteria=type=endpoint
